services:
  nextjs:
    build:
      context: ../..
      dockerfile: docker/frontend/prod.Dockerfile
    container_name: nextjs
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`lordsholtodouglas.com`) || Host(`www.lordsholtodouglas.com`) || Host(`ca.lordsholtodouglas.com`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=le"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

networks:
  app-network:
    external: true
