version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp_app
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../wp/plugins:/var/www/html/wp-content/plugins
      - ../wp/themes:/var/www/html/wp-content/themes
      - ../wp/uploads:/var/www/html/wp-content/uploads
      - wordpress_data:/var/www/html

    labels:
      - "traefik.enable=true"

      # Router (domain)
      - "traefik.http.routers.wordpress.rule=Host(`api.lordsholtodouglas.com`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"

      # FastCGI â†’ WordPress PHP-FPM
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=9000"

volumes:
  db_data:
  wordpress_data:
  letsencrypt:
